Repository vinitshahdeo/PortScanner, pull requests merged in 2020-06, with the labels that each got.

#4 Solves issue #1 and modernizes for Python 3.8
  scanner.py
Labels: python3

#20 Resolves relative path issue on Windows
  src/multi/__init__.py
  src/multi/scanner_thread.py
  src/scanner.py
Labels: bug, need review

#21 Added documentation
  docs/Documentation.docx
  docs/documentation.md
  src/multi/__init__.py
  src/multi/scanner_thread.py
  src/scanner.py
Labels: documentation, need review

#22 Updated Contributors section
  README.md
Labels: documentation, need review

#23 IP scanning feature added.
  .gitignore
  config.json
  src/ipscanner.py
  src/multi/scanner_thread.py
Labels: need review

#26 Added Code of Conduct
  CODE_OF_CONDUCT.md
Labels: documentation, need review

#27 Added CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, need review

#30 [Documentation] Updated README.md + Added community guidelines
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: need review

#31 Added Contribution Guidelines
  README.md
Labels: documentation, need review

#34 Fixes #33
  _config.yml
Labels: bug, need review
